# Generated by Django 4.0.5 on 2022-12-21 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0054_alter_ngssrestriction_inclusive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="\nThe name of this requirement. No two schedules can match in all of the fields\n`[name, semester, person]`\n",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "credits",
                    models.IntegerField(
                        help_text="\nThe number of credits required for this degree.    \n"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DegreeRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        help_text="\nThe academic semester this degree requirement is applicable to.\n",
                        max_length=5,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="\nThe name of this requirement.\n", max_length=255),
                ),
                (
                    "num_courses",
                    models.IntegerField(
                        help_text="\nThe number of courses required to fulfil this requirement. Can be null if this\nrequirement does not have a number of courses associated. Note that only one of\nnum_courses and num_credits should be null.\n",
                        null=True,
                    ),
                ),
                (
                    "num_credits",
                    models.IntegerField(
                        help_text="\nThe number of courses units (CUs) required to fulfil this requirement. Can be null if this\nrequirement does not have a number of CUs. Note that only one of num_courses and num_credits should\nbe null.\n",
                        null=True,
                    ),
                ),
                (
                    "inclusive",
                    models.BooleanField(
                        help_text="\nWhether the `topics` fields are the courses that fulfill this requirement (inclusive -> True),\nor are the set of courses that do not fulfill the requirement (exclusive -> False).\n"
                    ),
                ),
                (
                    "degree",
                    models.ForeignKey(
                        default=None,
                        help_text="\nThe degree this requirement falls under.\n",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="degree.degree",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(related_name="degree_requirements", to="courses.topic"),
                ),
            ],
            options={
                "unique_together": {("name", "semester", "degree")},
            },
        ),
        migrations.CreateModel(
            name="DegreePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="\nThe user's nick-name for the degree plan. No two plans can match in all of the fields\n`[name, person]`\n",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cart", models.ManyToManyField(to="courses.course")),
                (
                    "degree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="degree.degree"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="The person (user) to which the degree plan belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "person")},
            },
        ),
        migrations.CreateModel(
            name="DegreeFulfillment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        db_index=True,
                        help_text="\nThe academic semester this degree fulfillment is applicable to.\n",
                        max_length=5,
                    ),
                ),
                (
                    "overridden",
                    models.BooleanField(
                        help_text="\nWhether this is an override for one or more requirements.\n"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="\nThe fulfilling course.\n",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                    ),
                ),
                (
                    "degree_plan",
                    models.ForeignKey(
                        default=None,
                        help_text="\nThe degree plan this semester plan is a part of.\n",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fulfillments",
                        to="degree.degreeplan",
                    ),
                ),
                (
                    "fulfilled_requirements",
                    models.ManyToManyField(
                        help_text="\nThe requirement(s) this fulfils.\n",
                        to="degree.degreerequirement",
                    ),
                ),
            ],
            options={
                "unique_together": {("degree_plan", "semester", "course")},
            },
        ),
    ]
