# Generated by Django 3.2.20 on 2023-10-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="degree_plan",
            field=models.ForeignKey(
                help_text="\nThe degree plan that has this rule. Null if this rule has a parent.\n",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="degree.degreeplan",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="parent",
            field=models.ForeignKey(
                help_text="\nThis rule's parent Rule if it has one. Null if this is a top level rule\n(ie, degree_plan is not null)\n",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="degree.rule",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="q",
            field=models.TextField(
                blank=True,
                help_text="\nString representing a Q() object that returns the set of courses\nsatisfying this rule. Only non-null/non-empty if this is a Rule leaf.\nThis Q object is expected to be normalized before it is serialized\nto a string.\n",
                max_length=1000,
            ),
        ),
    ]
