# Generated by Django 5.0.2 on 2025-04-06 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoubleCountAllow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "max_courses",
                    models.PositiveSmallIntegerField(
                        help_text="\nThe maximum number of courses you can count for both rules.\nIf null, there is no limit, and max_credits must not be null.\n",
                        null=True,
                    ),
                ),
                (
                    "max_credits",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="\nThe maximum number of CUs you can count for both rules.\nIf null, there is no limit, and max_courses must not be null.\n",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "other_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="degree.rule",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="\nA rule in the double count allowance.\n",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="degree.rule",
                    ),
                ),
            ],
        ),
    ]
