# Generated by Django 3.2.23 on 2024-02-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeplan',
            name='degrees',
            field=models.ManyToManyField(blank=True, help_text='The degrees this degree plan is associated with.', to='degree.Degree'),
        ),
    ]
