# Generated by Django 5.0.2 on 2025-03-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillment",
            name="selected_rules",
            field=models.ManyToManyField(
                blank=True,
                help_text="\nThe rules this course fulfills that should be shown in the open-ended rule box \n(as opposed to the expandable box). Blank if this course should not be included in\nany open-ended rule boxes.\n",
                related_name="+",
                to="degree.rule",
            ),
        ),
    ]
