# Generated by Django 3.2.20 on 2023-09-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="\nThe name of this requirement, e.g., General Education, Foundations\n",
                        max_length=256,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="\nThe canonical code for this requirement, e.g., U-GE-FND\n",
                        max_length=32,
                    ),
                ),
                (
                    "min_cus",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="\nThe minimum number of CUs required to qualify for this degree requirement\n",
                        max_digits=4,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "q",
                    models.TextField(
                        help_text="\nString representing a Q() object that returns the set of courses satisfying this rule.\n",
                        max_length=1000,
                    ),
                ),
                (
                    "min_num",
                    models.IntegerField(
                        help_text="\nThe minimum number of courses required for this rule.\n",
                        null=True,
                    ),
                ),
                (
                    "max_num",
                    models.IntegerField(
                        help_text="\nThe maximum number of courses required for this rule.\n",
                        null=True,
                    ),
                ),
                (
                    "min_cus",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="\nThe minimum number of CUs required for this rule.\n",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "max_cus",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="\nThe maximum number of CUs required for this rule.\n",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        help_text="\nThe degree requirement that has this rule.\n",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="degree.requirement",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="degreefulfillment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="degreefulfillment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="degreefulfillment",
            name="degree_plan",
        ),
        migrations.RemoveField(
            model_name="degreefulfillment",
            name="fulfilled_requirements",
        ),
        migrations.AlterUniqueTogether(
            name="degreerequirement",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="degreerequirement",
            name="degree",
        ),
        migrations.RemoveField(
            model_name="degreerequirement",
            name="topics",
        ),
        migrations.AddField(
            model_name="degreeplan",
            name="concentration",
            field=models.CharField(
                help_text="\nThe concentration code for this degree plan, e.g., BMAT\n",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="degreeplan",
            name="major",
            field=models.CharField(
                default="",
                help_text="\nThe major code for this degree plan, e.g., BIOL\n",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="degreeplan",
            name="program",
            field=models.CharField(
                default="",
                help_text="\nThe program code for this degree plan, e.g., EU_BSE\n",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="degreeplan",
            name="year",
            field=models.IntegerField(
                default=2023, help_text="\nThe effective year of this degree plan, e.g., 2023\n"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="degreeplan",
            name="degree",
            field=models.CharField(
                help_text="\nThe degree code for this degree plan, e.g., BSE\n", max_length=32
            ),
        ),
        migrations.AlterUniqueTogether(
            name="degreeplan",
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name="Degree",
        ),
        migrations.DeleteModel(
            name="DegreeFulfillment",
        ),
        migrations.DeleteModel(
            name="DegreeRequirement",
        ),
        migrations.AddField(
            model_name="requirement",
            name="degree_plan",
            field=models.ForeignKey(
                help_text="\nThe degree plan that has this requirement.\n",
                on_delete=django.db.models.deletion.CASCADE,
                to="degree.degreeplan",
            ),
        ),
        migrations.RemoveField(
            model_name="degreeplan",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="degreeplan",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="degreeplan",
            name="name",
        ),
        migrations.RemoveField(
            model_name="degreeplan",
            name="person",
        ),
        migrations.RemoveField(
            model_name="degreeplan",
            name="updated_at",
        ),
    ]
