# Generated by Django 5.0.2 on 2025-03-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0002_fulfillment_selected_rules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fulfillment",
            name="selected_rules",
        ),
        migrations.AddField(
            model_name="fulfillment",
            name="unselected_rules",
            field=models.ManyToManyField(
                blank=True,
                help_text="\nThe rules this course fulfills that should be shown in the open-ended rule box \n(as opposed to the expandable box). Blank if this course should not be included in\nany open-ended rule boxes.\n",
                related_name="selected",
                to="degree.rule",
            ),
        ),
    ]
