# Generated by Django 3.2.20 on 2023-10-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0002_auto_20230924_1412"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degreeplan",
            name="program",
            field=models.CharField(
                choices=[
                    ("EU_BSE", "Engineering BSE"),
                    ("EU_BAS", "Engineering BAS"),
                    ("AU_BA", "College BA"),
                    ("WU_BS", "Wharton BS"),
                ],
                help_text="\nThe program code for this degree plan, e.g., EU_BSE\n",
                max_length=32,
            ),
        ),
        migrations.RemoveField(
            model_name="requirement",
            name="degree_plan",
        ),
        migrations.AddField(
            model_name="requirement",
            name="degree_plan",
            field=models.ManyToManyField(
                help_text="\nThe degree plan(s) that have this requirement.\n",
                to="degree.DegreePlan",
            ),
        ),
    ]
