# Generated by Django 5.0.2 on 2025-12-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0002_fulfillment_legal_fulfillment_unselected_rules_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fulfillment",
            name="legal",
            field=models.BooleanField(
                default=True,
                help_text="\nTrue if course associated with this fulfillment isn't illegally double counted anywhere,\nfalse otherwise.\n",
            ),
        ),
        migrations.AlterField(
            model_name="fulfillment",
            name="unselected_rules",
            field=models.ManyToManyField(
                blank=True,
                help_text="\nThe rules this course fulfills that should be shown in the open-ended rule box\n(as opposed to the expandable box). Blank if this course should not be included in\nany open-ended rule boxes.\n",
                related_name="unselected",
                to="degree.rule",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="can_double_count_with",
            field=models.ManyToManyField(
                blank=True,
                help_text="\nParent rules that can double count with this rule.\n(i.e. if this rule is Quantitative Data Analysis (a College Foundations req),\nthen this field would contain the General Educations: Sector rule as well as\nthe Major in ___ rule.)\n",
                to="degree.rule",
            ),
        ),
    ]
