# Generated by Django 3.2.20 on 2023-11-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0002_auto_20231027_1120"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="degreeplan",
            constraint=models.UniqueConstraint(
                fields=("program", "degree", "major", "concentration", "year"),
                name="unique degreeplan",
            ),
        ),
    ]
