# Generated by Django 5.0.2 on 2025-04-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0065_topic_historical_probabilities_fall_and_more"),
        ("degree", "0003_remove_fulfillment_selected_rules_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="fulfillment",
        #     name="unselected_rules",
        # ),
        migrations.AddField(
            model_name="fulfillment",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                help_text="\nThe attributes associated with this course.\n",
                to="courses.attribute",
            ),
        ),
    ]
