# Generated by Django 5.0.2 on 2026-04-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0003_alter_degree_program_alter_fulfillment_legal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degree",
            name="degree",
            field=models.CharField(
                help_text="\nThe degree code for this degree, e.g., BSE\n", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="degree",
            name="program",
            field=models.CharField(
                choices=[
                    ("EU_BSE", "Engineering BSE"),
                    ("EU_BAS", "Engineering BAS"),
                    ("AU_BA", "College BA"),
                    ("WU_BS", "Wharton BS"),
                    ("NU_BSN", "Nursing BSN"),
                    ("EU_BAS_MANT", "M&T BAS (SEAS)"),
                    ("EU_BSE_MANT", "M&T BSE (SEAS)"),
                    ("WU_BS_MANT", "M&T BS (Wharton)"),
                ],
                help_text="\nThe program code for this degree, e.g., EU_BSE\n",
                max_length=16,
            ),
        ),
    ]
