# Generated by Django 5.0.2 on 2026-04-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0003_alter_degree_program_alter_fulfillment_legal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillment",
            name="overrides",
            field=models.ManyToManyField(
                blank=True,
                help_text="\nRules this course is manually overridden to count for, bypassing the normal Q filter\ncheck. Use this to handle edge cases where a course should fulfill a requirement\neven though it doesn't technically satisfy the rule's conditions.\n",
                related_name="overridden_fulfillments",
                to="degree.rule",
            ),
        ),
        migrations.AlterField(
            model_name="degree",
            name="program",
            field=models.CharField(
                choices=[
                    ("EU_BSE", "Engineering BSE"),
                    ("EU_BAS", "Engineering BAS"),
                    ("AU_BA", "College BA"),
                    ("WU_BS", "Wharton BS"),
                    ("NU_BSN", "Nursing BSN"),
                ],
                help_text="\nThe program code for this degree, e.g., EU_BSE\n",
                max_length=16,
            ),
        ),
    ]
