# Generated by Django 3.2.23 on 2023-11-17 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0061_merge_20231112_1524"),
        ("degree", "0003_degreeplan_unique degreeplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="credits",
            field=models.DecimalField(
                decimal_places=2,
                help_text="\nThe minimum number of CUs required for this rule. Only non-null\nif this is a Rule leaf.\n",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="UserDegreePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The user's nickname for the degree plan.", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "courses",
                    models.ManyToManyField(
                        help_text="Courses used to fulfill the degree_plan.", to="courses.Course"
                    ),
                ),
                (
                    "degree_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="degree.degreeplan"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="the person (user) to which the schedule belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="userdegreeplan",
            constraint=models.UniqueConstraint(
                fields=("name", "person"), name="user_degreeplan_name_person"
            ),
        ),
    ]
