# Generated by Django 5.0.2 on 2026-02-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0003_alter_degree_program_alter_fulfillment_legal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degree",
            name="program",
            field=models.CharField(
                choices=[
                    ("EU_BSE", "Engineering BSE"),
                    ("EU_BAS", "Engineering BAS"),
                    ("AU_BA", "College BA"),
                    ("WU_BS", "Wharton BS"),
                    ("NU_BSN", "Nursing BSN"),
                ],
                help_text="\nThe program code for this degree, e.g., EU_BSE\n",
                max_length=16,
            ),
        ),
    ]
