# Generated by Django 3.2.20 on 2023-10-06 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0003_auto_20231001_1145"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="max_cus",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="max_num",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="min_cus",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="min_num",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="requirement",
        ),
        migrations.AddField(
            model_name="rule",
            name="cus",
            field=models.DecimalField(
                decimal_places=1,
                help_text="\nThe minimum number of CUs required for this rule. Only non-null\nif this is a Rule leaf.\n",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="degree_plan",
            field=models.ForeignKey(
                default=0,
                help_text="\nThe degree plan that has this rule.\n",
                on_delete=django.db.models.deletion.CASCADE,
                to="degree.degreeplan",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rule",
            name="num",
            field=models.IntegerField(
                help_text="\nThe minimum number of courses or subrules required for this rule.\n",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="parent",
            field=models.ForeignKey(
                help_text="\nThis rule's parent Rule if it has one.\n",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="degree.rule",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="q",
            field=models.TextField(
                help_text="\nString representing a Q() object that returns the set of courses\nsatisfying this rule. Only non-empty if this is a Rule leaf.\n",
                max_length=1000,
            ),
        ),
        migrations.DeleteModel(
            name="Requirement",
        ),
    ]
