# Generated by Django 3.2.23 on 2024-02-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0003_alter_fulfillment_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fulfillment",
            name="historical_course",
        ),
    ]
