# Generated by Django 5.0.2 on 2026-01-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0003_alter_fulfillment_legal_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(fields=["parent"], name="degree_rule_parent__876303_idx"),
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(fields=["id", "q"], name="degree_rule_id_f686f2_idx"),
        ),
    ]
