# Generated by Django 5.0.2 on 2026-02-13 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0003_alter_degree_program_alter_fulfillment_legal_and_more"),
        ("degree", "0003_alter_fulfillment_legal_and_more"),
    ]

    operations = []
