# Generated by Django 5.0.2 on 2026-08-18 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0004_fulfillment_overrides"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="can_double_count_with",
        ),
    ]
