# Generated by Django 3.2.20 on 2023-10-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0004_auto_20231006_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='cus',
            new_name='credits',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='num',
        ),
        migrations.AddField(
            model_name='rule',
            name='num_courses',
            field=models.IntegerField(help_text='\nThe minimum number of courses or subrules required for this rule. Only non-null\nif this is a Rule leaf.\n', null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='parent',
            field=models.ForeignKey(help_text="\nThis rule's parent Rule if it has one.\n", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='degree.rule'),
        ),
    ]
