# Generated by Django 3.2.23 on 2023-11-24 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0004_auto_20231117_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleCountRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_courses', models.PositiveSmallIntegerField(help_text='\nThe maximum number of courses you can count for both rules.\n', null=True)),
                ('max_credits', models.DecimalField(decimal_places=2, help_text='\nThe maximum number of CUs you can count for both rules.\n', max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_code', models.CharField(blank=True, db_index=True, help_text='The dash-joined department and code of the course, e.g. `CIS-120` for CIS-120.', max_length=16)),
                ('semester', models.CharField(help_text='\nThe semester of the course (of the form YYYYx where x is A [for spring],\nB [summer], or C [fall]), e.g. `2019C` for fall 2019. Null if this fulfillment\ndoes not yet have a semester\n', max_length=5, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='rule',
            name='num_course_credits_gt_0',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='num_courses',
        ),
        migrations.RemoveField(
            model_name='userdegreeplan',
            name='courses',
        ),
        migrations.AddField(
            model_name='rule',
            name='num',
            field=models.PositiveSmallIntegerField(help_text='\nThe minimum number of courses or subrules required for this rule.\n', null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='degree_plan',
            field=models.ForeignKey(help_text='\nThe degree plan that has this rule. Null if this rule has a parent.\n', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='degree.degreeplan'),
        ),
        migrations.AlterField(
            model_name='userdegreeplan',
            name='degree_plan',
            field=models.ForeignKey(help_text='The degree plan with which this is associated', on_delete=django.db.models.deletion.CASCADE, to='degree.degreeplan'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='rules',
            field=models.ManyToManyField(blank=True, help_text='\nThe rules this course fulfills. Blank if this course does not apply\nto any rules.\n', related_name='fulfillments', to='degree.Rule'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='user_degree_plan',
            field=models.ForeignKey(help_text='The user degree plan with which this fulfillment is associated', on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='degree.userdegreeplan'),
        ),
        migrations.AddField(
            model_name='doublecountrestriction',
            name='degree_plan',
            field=models.ForeignKey(help_text='The degree plan with which this is associated', on_delete=django.db.models.deletion.CASCADE, related_name='double_count_restrictions', to='degree.degreeplan'),
        ),
        migrations.AddField(
            model_name='doublecountrestriction',
            name='other_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='degree.rule'),
        ),
        migrations.AddField(
            model_name='doublecountrestriction',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='degree.rule'),
        ),
    ]
