# Generated by Django 5.0.2 on 2026-09-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0005_remove_rule_can_double_count_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="block_type",
            field=models.CharField(
                blank=True,
                help_text="\nThe type of the audit block this rule came from, e.g. MAJOR or OTHER. Blank for\nrules that did not come from a Path@Penn audit. Together with `block_value` this\nidentifies the block, which is what `share_targets` is expressed in terms of.\n",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="block_value",
            field=models.CharField(
                blank=True,
                help_text="\nThe code of the audit block this rule came from, e.g. CMPE for a major block or\nU-SEAS-SSH for a named other block. Blank for rules not from a Path@Penn audit.\n",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="share_targets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='\nWhat this rule is allowed to double count with, as a list of\n{"kind": ..., "value": ...} objects taken from the audit\'s ShareWith\n(NONEXCLUSIVE) qualifiers. `kind` is a block type or the literal THISBLOCK, and\n`value` names a specific block when the qualifier does. An empty list means this\nrule may not double count with anything.\n',
            ),
        ),
    ]
