# Generated by Django 3.2.23 on 2023-12-01 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("degree", "0005_auto_20231123_2256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fulfillment",
            name="full_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The dash-joined department and code of the course, e.g. `CIS-120`",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="fulfillment",
            name="semester",
            field=models.CharField(
                help_text="\nThe semester of the course (of the form YYYYx where x is A [for spring],\nB [summer], or C [fall]), e.g. `2019C` for fall 2019. Null if this fulfillment\ndoes not yet have a semester.\n",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="parent",
            field=models.ForeignKey(
                help_text="\nThis rule's parent Rule if it has one. Null if this is a top level rule\n(i.e., degree_plan is not null)\n",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="degree.rule",
            ),
        ),
        migrations.AlterField(
            model_name="userdegreeplan",
            name="degree_plan",
            field=models.ForeignKey(
                help_text="The degree plan with which this is associated.",
                on_delete=django.db.models.deletion.CASCADE,
                to="degree.degreeplan",
            ),
        ),
        migrations.AlterField(
            model_name="userdegreeplan",
            name="person",
            field=models.ForeignKey(
                help_text="The user to which the schedule belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
