# Generated by Django 3.2.20 on 2023-10-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0005_auto_20231012_1226"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="title",
            field=models.CharField(
                blank=True, help_text="\nThe title for this rule.\n", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="degreeplan",
            name="concentration",
            field=models.CharField(
                help_text="\nThe concentration code for this degree plan, e.g., BMAT\n",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="degreeplan",
            name="degree",
            field=models.CharField(
                help_text="\nThe degree code for this degree plan, e.g., BSE\n", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="degreeplan",
            name="major",
            field=models.CharField(
                help_text="\nThe major code for this degree plan, e.g., BIOL\n", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="degreeplan",
            name="program",
            field=models.CharField(
                choices=[
                    ("EU_BSE", "Engineering BSE"),
                    ("EU_BAS", "Engineering BAS"),
                    ("AU_BA", "College BA"),
                    ("WU_BS", "Wharton BS"),
                ],
                help_text="\nThe program code for this degree plan, e.g., EU_BSE\n",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="credits",
            field=models.DecimalField(
                decimal_places=2,
                help_text="\nThe minimum number of CUs required for this rule. Only non-null\nif this is a Rule leaf. Can be \n",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="num_courses",
            field=models.PositiveSmallIntegerField(
                help_text="\nThe minimum number of courses or subrules required for this rule. Only non-null\nif this is a Rule leaf.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="q",
            field=models.TextField(
                help_text="\nString representing a Q() object that returns the set of courses\nsatisfying this rule. Only non-null/non-empty if this is a Rule leaf.\nThis Q object is expected to be normalized before it is serialized\nto a string.\n",
                max_length=1000,
            ),
        ),
        migrations.AddConstraint(
            model_name="rule",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("credits__isnull", True), ("credits__gt", 0), _connector="OR"),
                    models.Q(
                        ("num_courses__isnull", True), ("num_courses__gt", 0), _connector="OR"
                    ),
                ),
                name="num_course_credits_gt_0",
            ),
        ),
    ]
