# Generated by Django 3.2.23 on 2024-02-06 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_merge_20231112_1524'),
        ('degree', '0006_auto_20240205_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillment',
            name='historical_course',
            field=models.ForeignKey(help_text='\nThe last offering of the course with the full code, or null if\nthere is no such historical course.\n', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
    ]
