# Generated by Django 5.0.2 on 2025-04-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0065_topic_historical_probabilities_fall_and_more"),
        ("degree", "0005_fulfillment_unselected_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillment",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                help_text="\nThe attributes associated with this course.\n",
                to="courses.attribute",
            ),
        ),
    ]
