# Generated by Django 3.2.23 on 2024-02-07 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0061_merge_20231112_1524'),
        ('degree', '0006_auto_20240205_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeplan',
            name='degrees',
            field=models.ManyToManyField(help_text='The degrees this degree plan is associated with.', to='degree.Degree'),
        ),
        migrations.AlterField(
            model_name='degreeplan',
            name='person',
            field=models.ForeignKey(help_text='The user the degree plan belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doublecountrestriction',
            name='max_courses',
            field=models.PositiveSmallIntegerField(help_text='\nThe maximum number of courses you can count for both rules.\nIf null, there is no limit, and max_credits must not be null.\n', null=True),
        ),
        migrations.AlterField(
            model_name='doublecountrestriction',
            name='max_credits',
            field=models.DecimalField(decimal_places=2, help_text='\nThe maximum number of CUs you can count for both rules.\nIf null, there is no limit, and max_credits must not be null.\n', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='doublecountrestriction',
            name='rule',
            field=models.ForeignKey(help_text='\nA rule in the double count restriction.\n', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='degree.rule'),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='historical_course',
            field=models.ForeignKey(help_text='\nThe last offering of the course with the full code, or null if\nthere is no such historical course.\n', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='q',
            field=models.TextField(blank=True, help_text='\nString representing a Q() object that returns the set of courses\nsatisfying this rule. Non-empty iff this is a Rule leaf.\nThis Q object is expected to be normalized before it is serialized\nto a string.\n', max_length=1000),
        ),
    ]
