# Generated by Django 5.0.2 on 2026-09-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0006_rule_block_type_rule_block_value_rule_share_targets"),
    ]

    operations = [
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "program_code",
                    models.CharField(
                        help_text="\nThe Path@Penn program this came from, e.g. MATH-BA-GEN or MATH-MINOR. Kept because\nthe same major code can have different requirements depending on the degree it sits\nunder: CSCI as a College second major is not CSCI as an Engineering major.\n",
                        max_length=32,
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="The major or minor code, e.g. MATH.", max_length=4),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name, e.g. Mathematics.", max_length=128, null=True
                    ),
                ),
                (
                    "year",
                    models.IntegerField(help_text="The catalog year this came from, e.g. 2027."),
                ),
                (
                    "credits",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The minimum number of CUs required, if the block states one.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("concentration", models.CharField(max_length=4, null=True)),
                ("concentration_name", models.CharField(max_length=128, null=True)),
                (
                    "rules",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The rules of this component's own block.",
                        to="degree.rule",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="degreeplan",
            name="majors",
            field=models.ManyToManyField(
                blank=True,
                help_text="\nMajors beyond the one the plan's degree already includes. Each contributes only\nits own block, not the whole audit it was read from.\n",
                related_name="degree_plans",
                to="degree.major",
            ),
        ),
        migrations.CreateModel(
            name="Minor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "program_code",
                    models.CharField(
                        help_text="\nThe Path@Penn program this came from, e.g. MATH-BA-GEN or MATH-MINOR. Kept because\nthe same major code can have different requirements depending on the degree it sits\nunder: CSCI as a College second major is not CSCI as an Engineering major.\n",
                        max_length=32,
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="The major or minor code, e.g. MATH.", max_length=4),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name, e.g. Mathematics.", max_length=128, null=True
                    ),
                ),
                (
                    "year",
                    models.IntegerField(help_text="The catalog year this came from, e.g. 2027."),
                ),
                (
                    "credits",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The minimum number of CUs required, if the block states one.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "rules",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The rules of this component's own block.",
                        to="degree.rule",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="degreeplan",
            name="minors",
            field=models.ManyToManyField(
                blank=True,
                help_text="The minors this degree plan is associated with.",
                related_name="degree_plans",
                to="degree.minor",
            ),
        ),
        migrations.AddConstraint(
            model_name="major",
            constraint=models.UniqueConstraint(
                fields=("program_code", "year"), name="unique major"
            ),
        ),
        migrations.AddConstraint(
            model_name="minor",
            constraint=models.UniqueConstraint(
                fields=("program_code", "year"), name="unique minor"
            ),
        ),
    ]
