# Generated by Django 3.2.23 on 2023-12-13 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('degree', '0006_auto_20231201_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('EU_BSE', 'Engineering BSE'), ('EU_BAS', 'Engineering BAS'), ('AU_BA', 'College BA'), ('WU_BS', 'Wharton BS')], help_text='\nThe program code for this degree, e.g., EU_BSE\n', max_length=10)),
                ('degree', models.CharField(help_text='\nThe degree code for this degree, e.g., BSE\n', max_length=4)),
                ('major', models.CharField(help_text='\nThe major code for this degree, e.g., BIOL\n', max_length=4)),
                ('concentration', models.CharField(help_text='\nThe concentration code for this degree, e.g., BMAT\n', max_length=4, null=True)),
                ('year', models.IntegerField(help_text='\nThe effective year of this degree, e.g., 2023\n')),
            ],
        ),
        migrations.CreateModel(
            name='SatisfactionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfied', models.BooleanField(default=False, help_text='Whether the rule is satisfied')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdegreeplan',
            name='degree_plan',
        ),
        migrations.RemoveField(
            model_name='userdegreeplan',
            name='person',
        ),
        migrations.RemoveConstraint(
            model_name='degreeplan',
            name='unique degreeplan',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='concentration',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='major',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='program',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='year',
        ),
        migrations.RemoveField(
            model_name='doublecountrestriction',
            name='degree_plan',
        ),
        migrations.RemoveField(
            model_name='fulfillment',
            name='user_degree_plan',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='degree_plan',
        ),
        migrations.AddField(
            model_name='degreeplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degreeplan',
            name='name',
            field=models.CharField(default='', help_text="The user's nickname for the degree plan.", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degreeplan',
            name='person',
            field=models.ForeignKey(default='', help_text='The user the schedule belongs to.', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degreeplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='degree_plan',
            field=models.ForeignKey(default='', help_text='The degree plan with which this fulfillment is associated', on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='degree.degreeplan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='full_code',
            field=models.CharField(blank=True, db_index=True, help_text='The dash-joined department and code of the course, e.g., `CIS-120`', max_length=16),
        ),
        migrations.AlterField(
            model_name='rule',
            name='parent',
            field=models.ForeignKey(help_text="\nThis rule's parent Rule if it has one. Null if this is a top level rule\n(i.e., degree is not null).\n", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='degree.rule'),
        ),
        migrations.AddConstraint(
            model_name='degreeplan',
            constraint=models.UniqueConstraint(fields=('name', 'person'), name='degreeplan_name_person'),
        ),
        migrations.DeleteModel(
            name='UserDegreePlan',
        ),
        migrations.AddField(
            model_name='satisfactionstatus',
            name='degree_plan',
            field=models.ForeignKey(help_text='The degree plan that leads to the satisfaction of the rule', on_delete=django.db.models.deletion.CASCADE, related_name='satisfactions', to='degree.degreeplan'),
        ),
        migrations.AddField(
            model_name='satisfactionstatus',
            name='rule',
            field=models.ForeignKey(help_text='The rule that is satisfied', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='degree.rule'),
        ),
        migrations.AddConstraint(
            model_name='degree',
            constraint=models.UniqueConstraint(fields=('program', 'degree', 'major', 'concentration', 'year'), name='unique degree'),
        ),
        migrations.AddField(
            model_name='rule',
            name='degree',
            field=models.ForeignKey(help_text='\nThe degree plan that has this rule. Null if this rule has a parent.\n', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='degree.degree'),
        ),
        migrations.AlterField(
            model_name='degreeplan',
            name='degree',
            field=models.ForeignKey(help_text='The degree this is associated with.', on_delete=django.db.models.deletion.CASCADE, to='degree.degree'),
        ),
        migrations.AddConstraint(
            model_name='satisfactionstatus',
            constraint=models.UniqueConstraint(fields=('degree_plan', 'rule'), name='unique_satisfaction'),
        ),
    ]
