# Generated by Django 3.2.23 on 2023-12-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0007_auto_20231213_1757"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="q",
            field=models.TextField(
                blank=True,
                help_text="\nString representing a Q() object that returns the set of courses\nsatisfying this rule. Only non-empty if this is a Rule leaf.\nThis Q object is expected to be normalized before it is serialized\nto a string.\n",
                max_length=1000,
            ),
        ),
    ]
