# Generated by Django 3.2.23 on 2024-03-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0007_alter_dockedcourse_full_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="degree",
            name="concentration_name",
            field=models.CharField(
                help_text="\nThe name of the concentration for this degree, e.g., Science Technology & Society\n",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="degree",
            name="program",
            field=models.CharField(
                choices=[
                    ("EU_BSE", "Engineering BSE"),
                    ("EU_BAS", "Engineering BAS"),
                    ("AU_BA", "College BA"),
                    ("WU_BS", "Wharton BS"),
                    ("NU_BSN", "Nursing BSN"),
                ],
                help_text="\nThe program code for this degree, e.g., EU_BSE\n",
                max_length=10,
            ),
        ),
    ]
