# Generated by Django 5.0.2 on 2025-04-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0007_add_attributes_to_fulfillment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fulfillment",
            name="attributes",
        ),
    ]
