# Generated by Django 5.0.2 on 2026-09-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0007_major_degreeplan_majors_minor_degreeplan_minors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="transfer_credit_allowed",
            field=models.BooleanField(
                default=True,
                help_text="\nWhether AP, IB, transfer and advanced standing credit may count toward this rule.\nFalse when the audit block this rule came from caps such credit at zero, which\nDegreeWorks writes as a MAXCLASS or MAXCREDIT header qualifier restricted with\nDWTRANSFERSCHOOLID; the College's General Education Foundations block is one.\nA fulfillment is transfer credit when its semester is TRANSFER_CREDIT_SEMESTER.\n",
            ),
        ),
    ]
