# Generated by Django 3.2.24 on 2024-03-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_course_credits'),
        ('degree', '0007_alter_dockedcourse_full_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='\nThe semester taken, in the form YYYYx\n', max_length=5)),
                ('grade', models.CharField(help_text="\nThe user's grade for this course\n", max_length=2)),
                ('course', models.ForeignKey(help_text='\nA list of course codes that the user has already taken, matched with semester\n', on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.AlterField(
            model_name='degree',
            name='program',
            field=models.CharField(choices=[('EU_BSE', 'Engineering BSE'), ('EU_BAS', 'Engineering BAS'), ('AU_BA', 'College BA'), ('WU_BS', 'Wharton BS'), ('NU_BSN', 'Nursing BSN')], help_text='\nThe program code for this degree, e.g., EU_BSE\n', max_length=10),
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(db_index=True, help_text="\nThe user's current program (e.g. SEAS B.S.)\n", max_length=255)),
                ('courses', models.ForeignKey(blank=True, help_text='\nCourses already taken, prob a list of Course objects\n', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_date', models.CharField(help_text="\nThe user's expected graduation date (of the form YYYYx where x is A [for spring],\nB [summer], or C [fall]), e.g. `2019C` for fall 2019)\n", max_length=5)),
                ('courses_taken', models.ManyToManyField(help_text='\nA list of course codes that the user has already taken, matched with semester\n', related_name='degree_profiles', through='degree.CourseTaken', to='courses.Course')),
                ('degrees', models.ManyToManyField(help_text="\nThe user's current degree(s)\n", to='degree.Degree')),
                ('transcript', models.OneToOneField(help_text="The user's uploaded transcript parsed into a Transcript object (optional)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degree_profile', to='degree.transcript')),
                ('transfer_credits', models.ManyToManyField(help_text='\nTransfer credits\n', related_name='transfer_credit_profiles', to='courses.Course')),
                ('user_profile', models.OneToOneField(help_text='extending the user profile class from courses to store degree plan specific info', on_delete=django.db.models.deletion.CASCADE, related_name='degree_profile', to='courses.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='coursetaken',
            name='degree_profile',
            field=models.ForeignKey(help_text='\nThe degree profile belonging to the user that took this course\n', on_delete=django.db.models.deletion.CASCADE, to='degree.degreeprofile'),
        ),
        migrations.AddConstraint(
            model_name='coursetaken',
            constraint=models.UniqueConstraint(fields=('degree_profile', 'course', 'semester'), name='unique_course_taken'),
        ),
    ]
