# Generated by Django 3.2.23 on 2024-03-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0008_auto_20240327_2029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degree",
            name="credits",
            field=models.DecimalField(
                decimal_places=2,
                help_text="\nThe minimum number of CUs required for this degree.\n",
                max_digits=4,
                null=True,
            ),
        ),
    ]
