# Generated by Django 3.2.24 on 2024-03-24 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_course_credits'),
        ('degree', '0008_auto_20240324_1246'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursetaken',
            name='unique_course_taken',
        ),
        migrations.AlterField(
            model_name='coursetaken',
            name='degree_profile',
            field=models.ForeignKey(help_text='\nThe degree profile to which this course was taken\n', on_delete=django.db.models.deletion.CASCADE, to='degree.degreeprofile'),
        ),
        migrations.AlterField(
            model_name='degreeprofile',
            name='courses_taken',
            field=models.ManyToManyField(help_text='\nA list of course codes that the user has already taken, matched with semester\n', related_name='degree_profile', through='degree.CourseTaken', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='degreeprofile',
            name='transfer_credits',
            field=models.ManyToManyField(help_text='\nTransfer credits\n', related_name='transfer_credits_for', to='courses.Course'),
        ),
        migrations.AddConstraint(
            model_name='coursetaken',
            constraint=models.UniqueConstraint(fields=('degree_profile', 'course', 'semester'), name='unique-degree-profile'),
        ),
    ]
