# Generated by Django 5.0.2 on 2026-09-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0008_alter_degree_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="transfer_credit_allowed",
            field=models.BooleanField(
                default=True,
                help_text="\nWhether AP, IB, transfer and advanced standing credit may count toward this rule.\nA fulfillment is such credit when its semester is TRANSFER_CREDIT_SEMESTER.\n",
            ),
        ),
    ]
