# Generated by Django 5.0.2 on 2025-05-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0008_remove_fulfillment_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="can_double_count_with",
            field=models.ManyToManyField(
                blank=True,
                help_text="\nParent rules that can double count with this rule. \n(i.e. if this rule is Quantitative Data Analysis (a College Foundations req), \nthen this field would contain the General Educations: Sector rule as well as \nthe Major in ___ rule.) \n",
                to="degree.rule",
            ),
        ),
    ]
