# Generated by Django 5.0.2 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0008_alter_degree_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillment",
            name="ignore_prereqs",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "\nTrue if the user has chosen to dismiss unmet-prerequisite warnings for this"
                    " course in\nthis plan (e.g. they have a waiver or took an equivalent"
                    " elsewhere). Purely a display\npreference; it does not affect which rules the"
                    " course fulfills.\n"
                ),
            ),
        ),
    ]
