# Generated by Django 3.2.23 on 2024-03-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0009_alter_degree_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="degree",
            name="major_name",
            field=models.CharField(
                help_text="\nThe name of the major for this degree, e.g., Africana Studies\n",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="degree",
            name="concentration_name",
            field=models.CharField(
                help_text="\nThe name of the concentration for this degree, e.g., African American Studies\n",
                max_length=128,
                null=True,
            ),
        ),
    ]
