# Generated by Django 5.0.2 on 2025-05-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0009_rule_can_double_count_with"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fulfillment",
            name="unselected_rules",
        ),
        migrations.AddField(
            model_name="fulfillment",
            name="legal",
            field=models.BooleanField(
                default=True, help_text="\nTrue if legal, false otherwise.\n"
            ),
        ),
    ]
