# Generated by Django 3.2.24 on 2024-03-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0009_auto_20240324_1730'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursetaken',
            name='unique-degree-profile',
        ),
        migrations.AddConstraint(
            model_name='coursetaken',
            constraint=models.UniqueConstraint(fields=('degree_profile', 'course', 'semester'), name='unique-course-taken'),
        ),
        migrations.AddConstraint(
            model_name='degreeprofile',
            constraint=models.UniqueConstraint(fields=('user_profile',), name='unique-degree-profile'),
        ),
    ]
