# Generated by Django 3.2.24 on 2024-03-24 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_course_credits'),
        ('degree', '0010_auto_20240324_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetaken',
            name='course',
            field=models.ForeignKey(help_text='\nThe course code (e.g. CIS-1210) of the course taken\n', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
