# Generated by Django 3.2.24 on 2024-03-28 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_course_credits'),
        ('degree', '0011_alter_coursetaken_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetaken',
            name='course',
            field=models.ForeignKey(help_text='\nThe full-code (e.g. CIS-1210) of the course taken\n', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
