# Generated by Django 2.2 on 2019-05-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Registration",
        ),
    ]
