# Generated by Django 2.2.9 on 2020-01-31 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0006_auto_20191110_1357"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="muted",
            new_name="auto_resubscribe",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="auto_mute",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="muted_at",
        ),
    ]
