# Generated by Django 2.2.11 on 2020-04-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0008_registration_original_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration", name="canceled", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
