# Generated by Django 2.2.11 on 2020-04-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0009_auto_20200418_2117"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration", old_name="canceled_at", new_name="cancelled_at",
        ),
    ]
