# Generated by Django 3.1.1 on 2020-11-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0010_auto_20201002_0714"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="close_notification",
            field=models.BooleanField(
                default=False,
                help_text="Defaults to False.  Changes to True if the user opts-in to receive\n        a close notification (an alert when the section closes after an\n        alert was sent for it opening).\n",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="close_notification_sent",
            field=models.BooleanField(
                default=False,
                help_text="True if a close notification has been sent to the user, false otherwise.",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="close_notification_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="\nWhen was a close notification sent to the user as a result of this registration?\nNull if a close notification was not sent.\n",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="close_notification_sent_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unsent"),
                    ("LEG", "[Legacy] Sequence of course API requests"),
                    ("WEB", "Webhook"),
                    ("SERV", "Course Status Service"),
                    ("ADM", "Admin Interface"),
                ],
                default="",
                help_text='What triggered the close notification to be sent?  Options and meanings: <table width=100%><tr><td>""</td><td>"Unsent"</td></tr><tr><td>"LEG"</td><td>"[Legacy] Sequence of course API requests"</td></tr><tr><td>"WEB"</td><td>"Webhook"</td></tr><tr><td>"SERV"</td><td>"Course Status Service"</td></tr><tr><td>"ADM"</td><td>"Admin Interface"</td></tr></table>',
                max_length=16,
            ),
        ),
    ]
