# Generated by Django 3.1.4 on 2021-01-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0011_auto_20201108_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='source',
            field=models.CharField(choices=[('PCA', 'Penn Course Alert'), ('API', '3rd Party Integration'), ('PCP', 'Penn Course Plan'), ('PCR', 'Penn Course Review'), ('PM', 'Penn Mobile'), ('SCRIPT_PCN', 'The loadregistrations_pcn shell command'), ('SCRIPT_PCA', 'The loadregistrations_pca shell command')], help_text='Where did the registration come from? Options and meanings: <table width=100%><tr><td>"PCA"</td><td>"Penn Course Alert"</td></tr><tr><td>"API"</td><td>"3rd Party Integration"</td></tr><tr><td>"PCP"</td><td>"Penn Course Plan"</td></tr><tr><td>"PCR"</td><td>"Penn Course Review"</td></tr><tr><td>"PM"</td><td>"Penn Mobile"</td></tr><tr><td>"SCRIPT_PCN"</td><td>"The loadregistrations_pcn shell command"</td></tr><tr><td>"SCRIPT_PCA"</td><td>"The loadregistrations_pca shell command"</td></tr></table>', max_length=16),
        ),
    ]
