# Generated by Django 3.0.8 on 2020-12-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0011_auto_20201018_1401"),
        ("alert", "0011_auto_20201108_1535"),
    ]

    operations = []
