# Generated by Django 3.1.7 on 2021-03-04 17:59

import alert.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_userprofile_push_notifications'),
        ('alert', '0012_auto_20210103_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcaPopularityExtrema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The datetime at which the extrema were updated.')),
                ('highest_ratio_registration_volume', models.IntegerField(help_text='The registration volume of the most popular section.')),
                ('highest_ratio_section_capacity', models.IntegerField(help_text='The capacity of the most popular section. NOTE: must be strictly positive.', validators=[alert.models.PcaPopularityExtrema.validate_positive])),
                ('lowest_ratio_registration_volume', models.IntegerField(help_text='The registration volume of the least popular section.')),
                ('lowest_ratio_section_capacity', models.IntegerField(help_text='The capacity of the least popular section. NOTE: must be strictly positive.', validators=[alert.models.PcaPopularityExtrema.validate_positive])),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='section',
            field=models.ForeignKey(help_text='The section that the user registered to be notified about.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='courses.section'),
        ),
    ]
