# Generated by Django 3.2b1 on 2021-03-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0012_auto_20210328_2204"),
    ]

    operations = [
        migrations.AddField(
            model_name="adddropperiod",
            name="estimated_end",
            field=models.DateTimeField(
                blank=True,
                help_text="\n    This field estimates the end of the add/drop period based on the semester\n    and historical data, even if the end field hasn't been filled in yet.\n    The end of the add/drop period for this semester, if it is explicitly set, otherwise\nthe most recent non-null end to an add/drop period, otherwise (if none exist),\nestimate as October 12 @ 11:59pm ET (for a fall semester),\nor February 22 @ 11:59pm ET (for a spring semester),\nof the same year.\n",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adddropperiod",
            name="estimated_start",
            field=models.DateTimeField(
                blank=True,
                help_text="\nThis field estimates the start of the add/drop period based on the semester\nand historical data, even if the start field hasn't been filled in yet.\nIt equals the start of the add/drop period for this semester if it is explicitly set,\notherwise the most recent non-null start to an add/drop period, otherwise\n(if none exist), estimate as April 5 @ 7:00am ET of the same year (for a fall semester),\nor November 16 @ 7:00am ET of the previous year (for a spring semester).\n",
                null=True,
            ),
        ),
    ]
