# Generated by Django 3.2b1 on 2021-04-05 08:15

from django.db import migrations, models

import alert.models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0013_auto_20210328_2326"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcademandextrema",
            name="in_add_drop_period",
            field=models.BooleanField(
                default=False,
                help_text="Was this status update created during the add/drop period?",
            ),
        ),
        migrations.AddField(
            model_name="pcademandextrema",
            name="percent_through_add_drop_period",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="The percentage through the add/drop period at which this demand extrema change occurred. This percentage is constrained within the range [0,1].",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="adddropperiod",
            name="semester",
            field=models.CharField(
                db_index=True,
                help_text="\nThe semester of this add drop period (of the form YYYYx where x is\nA [for spring], or C [fall]), e.g. `2019C` for fall 2019.\n",
                max_length=5,
                unique=True,
                validators=[alert.models.validate_add_drop_semester],
            ),
        ),
        migrations.AlterField(
            model_name="pcademandextrema",
            name="semester",
            field=models.CharField(
                db_index=True,
                help_text="\nThe semester of this demand extrema (of the form YYYYx where x is\nA [for spring], B [summer], or C [fall]), e.g. `2019C` for fall 2019.\n",
                max_length=5,
            ),
        ),
    ]
