# Generated by Django 3.1.7 on 2021-03-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_userprofile_push_notifications'),
        ('alert', '0013_auto_20210304_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='section',
            field=models.ForeignKey(help_text='The section that the user registered to be notified about.', on_delete=django.db.models.deletion.CASCADE, related_name='registration_set', to='courses.section'),
        ),
    ]
