# Generated by Django 3.2b1 on 2021-04-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0014_auto_20210405_0415"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcademandextrema",
            name="in_add_drop_period",
            field=models.BooleanField(
                default=False,
                help_text="Was this demand extrema created during the add/drop period?",
            ),
        ),
    ]
