# Generated by Django 3.2b1 on 2021-04-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0015_alter_pcademandextrema_in_add_drop_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcademandextrema",
            name="percent_through_add_drop_period",
            field=models.FloatField(
                default=0,
                help_text="The percentage through the add/drop period at which this demand extrema change occurred. This percentage is constrained within the range [0,1].",
            ),
        ),
    ]
