# Generated by Django 3.2 on 2021-11-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0015_auto_20211010_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='head_registration',
            field=models.ForeignKey(blank=True, help_text="\nThe head of this registration's resubscribe chain (pointing to\nitself if this registration is the head of its chain).\n", null=True, on_delete=django.db.models.deletion.CASCADE, to='alert.registration'),
        ),
    ]
