# Generated by Django 3.2.9 on 2021-11-13 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0015_auto_20211010_1235"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pcademanddistributionestimate",
            name="csdv_75th_percentile",
        ),
        migrations.RemoveField(
            model_name="pcademanddistributionestimate",
            name="csdv_gamma_fit_mean_log_likelihood",
        ),
        migrations.RemoveField(
            model_name="pcademanddistributionestimate",
            name="csdv_gamma_param_alpha",
        ),
        migrations.RemoveField(
            model_name="pcademanddistributionestimate",
            name="csdv_gamma_param_loc",
        ),
        migrations.RemoveField(
            model_name="pcademanddistributionestimate",
            name="csdv_gamma_param_scale",
        ),
        migrations.RemoveField(
            model_name="pcademanddistributionestimate",
            name="csdv_mean",
        ),
        migrations.RemoveField(
            model_name="pcademanddistributionestimate",
            name="csdv_median",
        ),
        migrations.AddField(
            model_name="pcademanddistributionestimate",
            name="csprdv_lognorm_param_loc",
            field=models.FloatField(
                blank=True,
                help_text="The loc parameter of the fitted log-normal distribution on positive raw demand values from closed sections. Null if there are no closed sections that have positive raw demand values. The abbreviation 'csprdv' stands for 'closed section positive raw demand values'.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcademanddistributionestimate",
            name="csprdv_lognorm_param_scale",
            field=models.FloatField(
                blank=True,
                help_text="The scale parameter of the fitted log-normal distribution on positive raw demand values from closed sections. Null if there are no closed sections that have positive raw demand values. The abbreviation 'csprdv' stands for 'closed section positive raw demand values'.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcademanddistributionestimate",
            name="csprdv_lognorm_param_shape",
            field=models.FloatField(
                blank=True,
                help_text="The shape parameter of the fitted log-normal distribution on positive raw demand values from closed sections. Null if there are no closed sections that have positive raw demand values. The abbreviation 'csprdv' stands for 'closed section positive raw demand values'.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcademanddistributionestimate",
            name="csrdv_frac_zero",
            field=models.FloatField(
                blank=True,
                help_text="The fraction of closed sections' raw demand values that are 0 (non-positive), expressed as a float in the range [0,1]. Null if there are no closed sections. The abbreviation 'csrdv' stands for 'closed section raw demand values', not to be confused with 'csprdv', which stands for 'closed section positive raw demand values'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="head_registration",
            field=models.ForeignKey(
                blank=True,
                help_text="\nThe head of this registration's resubscribe chain (pointing to\nitself if this registration is the head of its chain).\n",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="alert.registration",
            ),
        ),
    ]
