# Generated by Django 4.0.3 on 2022-04-07 02:45

import django.db.models.deletion
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Registration = apps.get_model("alert", "Registration")
    Registration.objects.filter(head_registration__isnull=True).update(
        head_registration_id=models.F("id")
    )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0016_auto_20211113_1537"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name="registration",
            name="head_registration",
            field=models.ForeignKey(
                help_text="\nThe head of this registration's resubscribe chain (pointing to\nitself if this registration is the head of its chain). If you call `.save()`\non a registration  without setting its `head_registration` field, the overridden\n`Registration.save()` method will automatically set its `head_registration`\nto a self-reference.\n",
                on_delete=django.db.models.deletion.CASCADE,
                to="alert.registration",
            ),
        ),
    ]
