import {
	bigserial,
	boolean,
	pgTable,
	timestamp,
	varchar,
} from 'drizzle-orm/pg-core'

/**
 * This model was autogenerated / edited using drizzle-kit.
 * The source of truth is the model defined in the Django backend,
 * so be sure to sync changes with the backend.
 * DO NOT EXPORT/SYNC THIS MODEL.
 */
export const $authUser = pgTable('auth_user', {
	id: bigserial('id', { mode: 'bigint' }).primaryKey().notNull(),
	password: varchar('password', { length: 128 }).notNull(),
	lastLogin: timestamp('last_login', { withTimezone: true, mode: 'string' }),
	isSuperuser: boolean('is_superuser').notNull(),
	username: varchar('username', { length: 150 }).notNull(),
	firstName: varchar('first_name', { length: 150 }).notNull(),
	lastName: varchar('last_name', { length: 150 }).notNull(),
	email: varchar('email', { length: 254 }).notNull(),
	isStaff: boolean('is_staff').notNull(),
	isActive: boolean('is_active').notNull(),
	dateJoined: timestamp('date_joined', {
		withTimezone: true,
		mode: 'string',
	}).notNull(),
})
