FROM pennlabs/django-base:281d2f6446bb5381e1a2ecf39f6689b648d92ee6-3.10.1

LABEL maintainer="Penn Labs"

WORKDIR /backend

# Copy project dependencies
COPY pyproject.toml ./
COPY poetry.lock ./

# Install backend dependencies
RUN poetry install --no-root

# Alias runserver command
RUN echo 'alias runserver="python manage.py runserver 0.0.0.0:8000"' >> ~/.bashrc
