FROM pennlabs/django-base:3993245ba40f15f88ba53f5ae2548781f392a7c6-3.10.1

LABEL maintainer="Penn Labs"

WORKDIR /backend

# Copy project dependencies
COPY pyproject.toml ./
COPY poetry.lock ./

# Install backend dependencies
RUN poetry install --no-root

# Alias runserver command
RUN echo 'alias runserver="python manage.py runserver 0.0.0.0:8000"' >> ~/.bashrc
