version: "3"

services:
  db:
    image: postgis/postgis:15-master
    command: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=penn-courses
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/pgdata
  redis:
    image: redis:4.0
    ports:
      - "6379:6379"
