#!/bin/bash

# Django Migrate
/usr/local/bin/python3 /app/manage.py migrate --noinput

# Switch to project folder
cd /app/

# Run using Gunicorn + Uvicorn
exec /usr/local/bin/gunicorn -b 0.0.0.0:80 -w 4 -k uvicorn.workers.UvicornWorker PennCourses.asgi:application
