# Generated by Django 2.2.5 on 2019-10-27 19:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plan", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={("name", "semester", "person")},
        ),
    ]
