# Generated by Django 4.0.5 on 2022-10-31 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plan", "0006_alter_primaryscheduleloookup_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimarySchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="schedule",
            name="max_one_shared_per_person",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="is_shared",
        ),
        migrations.AddField(
            model_name="primaryschedule",
            name="person",
            field=models.ForeignKey(
                help_text="The person (user) to which the schedule belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="primaryschedule",
            name="schedule",
            field=models.ForeignKey(
                help_text="The schedule that is the primary schedule for the user.",
                on_delete=django.db.models.deletion.CASCADE,
                to="plan.schedule",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="primaryschedule",
            unique_together={("person",)},
        ),
    ]
