# Generated by Django 5.0.2 on 2025-01-26 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0009_alter_schedule_sections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Break",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_string",
                    models.CharField(
                        help_text="\nThis represents the location that the user can input themselves. \nWill use a building object from a drop down or have it validated or something so it can interact with map.\nDidn't want to run into issue of users creating arbitrary Room objects, so just using a char field\n",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="\nThe user's name for the break. No two breaks can match in all of the fields\n`[name, person]`\n",
                        max_length=255,
                    ),
                ),
                (
                    "meeting_times",
                    models.TextField(
                        blank=True,
                        help_text='\nA JSON-stringified list of meeting times of the form\n`{days code} {start time} - {end time}`, e.g.\n`["MWF 09:00 AM - 10:00 AM","F 11:00 AM - 12:00 PM","T 05:00 PM - 06:00 PM"]` for\nPHYS-151-001 (2020A). Each letter of the days code is of the form M, T, W, R, F for each\nday of the work week, respectively (and multiple days are combined with concatenation).\nTo access the Meeting objects for this section, the related field `meetings` can be used.\n',
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="The person (user) who created this break.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "person")},
            },
        ),
    ]
