# Generated by Django 5.0.2 on 2025-02-16 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0010_break"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="break",
            unique_together={("person",)},
        ),
        migrations.AlterField(
            model_name="break",
            name="location_string",
            field=models.CharField(
                help_text="\nThis represents the location that the user can input themselves.\nWill use a building object from a drop down or have it validated\nor something so it can interact with map.\nDidn't want to run into issue of users creating arbitrary\nRoom objects, so just using a char field\n",
                max_length=80,
                null=True,
            ),
        ),
    ]
