# Generated by Django 5.0.2 on 2025-02-16 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0011_alter_break_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="break",
            unique_together={("person", "meeting_times")},
        ),
    ]
