# Generated by Django 5.0.2 on 2025-02-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0012_alter_break_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="break",
            unique_together=set(),
        ),
    ]
