# Generated by Django 5.0.2 on 2025-02-16 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0013_alter_break_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="break",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("meeting_times__isnull", False),
                    models.Q(("meeting_times", ""), _negated=True),
                ),
                fields=("person", "meeting_times"),
                name="unique_break_meeting_times_per_person",
            ),
        ),
    ]
