# Generated by Django 5.0.2 on 2025-03-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0014_break_unique_break_meeting_times_per_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="breaks",
            field=models.ManyToManyField(
                blank=True,
                help_text="\nThe breaks which comprise the schedule. The semester of each of these breaks is assumed to\nmatch the semester defined by the semester field below.\n",
                to="plan.break",
            ),
        ),
    ]
