# Generated by Django 5.0.2 on 2025-05-13 23:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0015_schedule_breaks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="break",
            constraint=models.UniqueConstraint(
                condition=models.Q(("name__isnull", False), models.Q(("name", ""), _negated=True)),
                fields=("name", "person"),
                name="unique_break_name_per_person",
            ),
        ),
    ]
