# Generated by Django 5.0.2 on 2025-05-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0016_break_unique_break_name_per_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="break",
            name="checked",
            field=models.BooleanField(
                default=True,
                help_text="\nWhether or not the break has been checked by the user. This is used to\ndetermine if the break should be displayed in the user's schedule.\n",
            ),
        ),
    ]
