# Generated by Django 5.0.2 on 2026-02-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0017_break_checked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="break",
            name="name",
            field=models.CharField(
                help_text=(
                    "The user's name for the break. No two breaks can match in all of the fields"
                    " `[name, person]`\n"
                ),
                max_length=255,
            ),
        ),
    ]
