app = "penn-course-backend"
primary_region = "ewr"

[build]
  image = "pennlabs/penn-courses-backend"

[env]
  REDIS_HOST = "redis-courses.internal"
  # DOMAINS = "clubs-backend.internal,penn-clubs-frontend.internal,penn-clubs-frontend.fly.dev"
  DOMAINS = "*" # TODO: not sure why but was `*` before

[http_service]
  internal_port = 80
  force_https = false # TODO: eventually true lmao
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
