# Generated by Django 2.1.2 on 2018-10-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_id',
            field=models.SlugField(),
        ),
    ]
