# Generated by Django 2.2 on 2019-05-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_auto_20190508_0200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="credits",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
