# Generated by Django 2.2 on 2019-05-10 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_auto_20190508_0202"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Restriction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="section",
            name="prereq_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="courses.Department",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="restrictions",
            field=models.ManyToManyField(to="courses.Restriction"),
        ),
    ]
