# Generated by Django 2.2 on 2019-05-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_auto_20190510_0114"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=5)),
                ("code", models.CharField(max_length=10)),
                (
                    "school",
                    models.CharField(
                        choices=[
                            ("SEAS", "Engineering"),
                            ("WH17-", "Wharton 2017-"),
                            ("WH17+", "Wharton 2017+"),
                            ("SAS", "College"),
                        ],
                        max_length=5,
                    ),
                ),
                ("satisfies", models.BooleanField()),
                ("name", models.CharField(max_length=255)),
                (
                    "courses",
                    models.ManyToManyField(related_name="overrides", to="courses.Course"),
                ),
                (
                    "departments",
                    models.ManyToManyField(related_name="requirements", to="courses.Department"),
                ),
            ],
            options={
                "unique_together": {("semester", "code", "satisfies")},
            },
        ),
    ]
