# Generated by Django 2.2.1 on 2019-05-10 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_requirement"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="meeting",
            unique_together={("section", "day", "start", "end", "room")},
        ),
    ]
