# Generated by Django 2.2.1 on 2019-05-10 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_auto_20190510_0504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="courses.Course",
            ),
        ),
    ]
