# Generated by Django 2.2.1 on 2019-05-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_course_full_code"),
        ("courses", "0014_auto_20190518_1641"),
    ]

    operations = []
