# Generated by Django 2.2.1 on 2019-05-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_merge_20190518_2155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
