# Generated by Django 2.2.1 on 2019-05-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_auto_20190526_1655"),
        ("courses", "0017_auto_20190525_2235"),
    ]

    operations = []
