# Generated by Django 2.2.6 on 2019-11-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0022_auto_20191029_1927"),
        ("courses", "0023_auto_20191101_1717"),
    ]

    operations = []
