# Generated by Django 2.2.5 on 2019-11-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0025_auto_20191117_1309"),
        ("courses", "0024_merge_20191103_1941"),
    ]

    operations = []
