# Generated by Django 3.1.1 on 2020-11-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0030_auto_20201002_0714"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="push_notifications",
            field=models.BooleanField(
                default=False,
                help_text="\nDefaults to False, changed to True if the User enables mobile push notifications\nfor PCA, rather than text notifications.\n",
            ),
        ),
    ]
