# Generated by Django 3.2b1 on 2021-03-29 02:04

import django.core.validators
import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0031_userprofile_push_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="percent_open",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="\nIf this section is from the current semester, this is the percentage (expressed as a\ndecimal number between 0 and 1) of the period between the beginning of its\nadd/drop period and its last status update that this section was open\n(or 0 if it has had no status updates strictly within its add/drop period).\nIf this section is from a previous semester, this is the percentage of its\nwhole add/drop period that it was open.\n",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="registration_volume",
            field=models.PositiveIntegerField(
                default=0, help_text="The number of active PCA registrations watching this section."
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                django.db.models.expressions.Case(
                    django.db.models.expressions.When(
                        models.Q(("capacity__isnull", False), ("capacity__gt", 0)),
                        then=django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.comparison.Cast(
                                "registration_volume",
                                models.DecimalField(decimal_places=4, max_digits=11),
                            ),
                            "/",
                            django.db.models.functions.comparison.Cast(
                                "capacity", models.DecimalField(decimal_places=4, max_digits=11)
                            ),
                        ),
                    ),
                    default=None,
                    output_field=models.DecimalField(
                        blank=True, decimal_places=4, max_digits=11, null=True
                    ),
                ),
                name="raw_demand",
            ),
        ),
    ]
