# Generated by Django 3.2b1 on 2021-03-20 21:15

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_userprofile_push_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='registration_volume',
            field=models.IntegerField(default=0, help_text='The number of active PCA registrations watching this section.'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(django.db.models.expressions.Case(django.db.models.expressions.When(models.Q(('capacity__isnull', False), ('capacity__gt', 0)), then=django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Cast('registration_volume', models.DecimalField()), '/', django.db.models.functions.comparison.Cast('capacity', models.DecimalField()))), default=None, output_field=models.DecimalField()), name='raw_demand'),
        ),
    ]
