# Generated by Django 3.2b1 on 2021-03-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0032_auto_20210328_2204"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusupdate",
            name="in_add_drop_period",
            field=models.BooleanField(
                default=False,
                help_text="Was this status update created during the add/drop period?",
            ),
        ),
    ]
