# Generated by Django 3.2 on 2021-04-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0035_auto_20210406_0036"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="restrictions",
            field=models.ManyToManyField(
                blank=True,
                help_text="All registration Restriction objects to which this section is subject.",
                related_name="sections",
                to="courses.Restriction",
            ),
        ),
    ]
