# Generated by Django 4.0.3 on 2022-04-07 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0039_alter_course_primary_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="primary_listing",
            field=models.ForeignKey(
                help_text="\nThe primary Course object with which this course is crosslisted. The set of crosslisted\ncourses to which this course belongs can thus be accessed with the related field\n`listing_set` on the `primary_listing` course. If a course doesn't have any crosslistings,\nits `primary_listing` foreign key will point to itself. If you call `.save()` on a course\nwithout setting its `primary_listing` field, the overridden `Course.save()` method will\nautomatically set its `primary_listing` to a self-reference.\n",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_set",
                to="courses.course",
            ),
        ),
    ]
