# Generated by Django 4.0.3 on 2022-04-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0040_alter_course_primary_listing"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="section",
            name="raw_demand",
        ),
    ]
