# Generated by Django 4.0.3 on 2022-04-08 00:57

from django.db import migrations, models

from courses.management.commands.recompute_soft_state import recompute_has_reviews


def compute_has_reviews(apps, schema_editor):
    recompute_has_reviews()


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0041_remove_section_raw_demand"),
        ("review", "0004_auto_20200512_1526"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="has_reviews",
            field=models.BooleanField(
                default=False,
                help_text="\nA flag indicating whether this section has reviews (precomputed for efficiency).\n",
            ),
        ),
        migrations.RunPython(compute_has_reviews),
    ]
