# Generated by Django 4.0.2 on 2022-04-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0044_prengssrequirement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="pre_ngss_restrictions",
            field=models.ManyToManyField(
                blank=True,
                help_text="All pre-NGSS (deprecated since 2022C) registration Restriction objects to which this section is subject. This field will be empty for sections in 2022C or later.",
                related_name="sections",
                to="courses.PreNGSSRestriction",
            ),
        ),
    ]
