# Generated by Django 4.0.4 on 2022-04-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0045_course_crn_course_non_null_crn_semester_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="course",
            name="non_null_crn_semester_unique",
        ),
        migrations.RemoveField(
            model_name="course",
            name="crn",
        ),
        migrations.AddField(
            model_name="section",
            name="crn",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="\nThe CRN ID of the section.\nOnly available on sections after spring 2022 (i.e. after the NGSS transition).\n",
                max_length=8,
                null=True,
            ),
        ),
    ]
