# Generated by Django 4.0.4 on 2022-05-21 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_alter_section_pre_ngss_restrictions'),
        ('courses', '0046_remove_course_non_null_crn_semester_unique_and_more'),
    ]

    operations = [
    ]
