# Generated by Django 4.0.3 on 2022-05-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0046_remove_course_non_null_crn_semester_unique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.CharField(
                help_text="The room number, e.g. `101` for Wu and Chen Auditorium in Levine.",
                max_length=8,
            ),
        ),
    ]
