# Generated by Django 4.0.4 on 2022-05-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_merge_20220521_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='\nThe code of the restriction.\n', max_length=10, unique=True)),
                ('restriction_type', models.CharField(choices=[('ATTR', 'Attribute'), ('CAMP', 'Campus'), ('CLASI', 'Classification'), ('COHO', 'Cohort'), ('DEGR', 'Degree'), ('DIVI', 'Division'), ('LVL', 'Level'), ('MAJ', 'Major'), ('MIN', 'Minor'), ('PROG', 'Program'), ('SPEC', 'Special Approval')], db_index=True, help_text='\nWhat the restriction is based on (e.g., campus).\n<table width=100%><tr><td>"ATTR"</td><td>"Attribute"</td></tr><tr><td>"CAMP"</td><td>"Campus"</td></tr><tr><td>"CLASI"</td><td>"Classification"</td></tr><tr><td>"COHO"</td><td>"Cohort"</td></tr><tr><td>"DEGR"</td><td>"Degree"</td></tr><tr><td>"DIVI"</td><td>"Division"</td></tr><tr><td>"LVL"</td><td>"Level"</td></tr><tr><td>"MAJ"</td><td>"Major"</td></tr><tr><td>"MIN"</td><td>"Minor"</td></tr><tr><td>"PROG"</td><td>"Program"</td></tr><tr><td>"SPEC"</td><td>"Special Approval"</td></tr></table>', max_length=5)),
                ('include_or_exclude', models.BooleanField(help_text='\nWhether this is an include or exclude restriction. Corresponds to the incl_excl_ind\nresponse field. True if include (ie, incl_excl_ind is "I") and false if exclude ("E").\n')),
                ('description', models.TextField(help_text='\nThe registration restriction description.\n')),
                ('courses', models.ManyToManyField(blank=True, help_text='\nIndividual Course objects which have this restriction.\n', related_name='restrictions', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="\nA registration attribute code, for instance 'WUOM' for Wharton OIDD Operations track.\nSee [https://bit.ly/3L8bQDA](https://bit.ly/3L8bQDA)\nfor all options\n", max_length=10, unique=True)),
                ('description', models.TextField(help_text="\nThe registration attribute description, e.g. 'Wharton OIDD Operation'\nfor the WUOM attribute.\nSee [https://bit.ly/3L8bQDA](https://bit.ly/3L8bQDA) for all options.\n")),
                ('school', models.CharField(choices=[('SEAS', 'Engineering'), ('WH', 'Wharton'), ('DSGN', 'Design'), ('SAS', 'School of Arts and Sciences'), ('NURS', 'Nursing'), ('VIPER', 'VIPER'), ('VET', 'Veterinary'), ('GSE', 'GSE'), ('OTHER', 'Other')], db_index=True, help_text='\nWhat school this requirement belongs to, e.g. `SAS` for the SAS \'Formal Reasoning Course\'\nrequirement satisfied by CIS-120. Options and meanings:\n<table width=100%><tr><td>"SEAS"</td><td>"Engineering"</td></tr><tr><td>"WH"</td><td>"Wharton"</td></tr><tr><td>"DSGN"</td><td>"Design"</td></tr><tr><td>"SAS"</td><td>"School of Arts and Sciences"</td></tr><tr><td>"NURS"</td><td>"Nursing"</td></tr><tr><td>"VIPER"</td><td>"VIPER"</td></tr><tr><td>"VET"</td><td>"Veterinary"</td></tr><tr><td>"GSE"</td><td>"GSE"</td></tr><tr><td>"OTHER"</td><td>"Other"</td></tr></table>', max_length=5)),
                ('courses', models.ManyToManyField(blank=True, help_text='\nIndividual Course objects which have this attribute\n', related_name='attributes', to='courses.course')),
            ],
        ),
    ]
