# Generated by Django 4.0.4 on 2022-05-30 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0047_alter_room_number"),
        ("courses", "0048_alter_attribute_school"),
    ]

    operations = []
