# Generated by Django 4.0.4 on 2022-05-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0049_merge_20220529_2355"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ngssrestriction",
            old_name="include_or_exclude",
            new_name="inclusive",
        ),
        migrations.AlterField(
            model_name="attribute",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="\nA registration attribute code, for instance 'WUOM' for Wharton OIDD Operations track.\n",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="description",
            field=models.TextField(
                help_text="\nThe registration attribute description, e.g. 'Wharton OIDD Operation'\nfor the WUOM attribute.\n"
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="school",
            field=models.CharField(
                choices=[
                    ("SAS", "School of Arts and Sciences"),
                    ("LPS", "College of Liberal and Professional Studies"),
                    ("SEAS", "Engineering"),
                    ("DSGN", "Design"),
                    ("GSE", "Graduate School of Education"),
                    ("LAW", "Law School"),
                    ("MED", "School of Medicine"),
                    ("MODE", "Grade Mode"),
                    ("VET", "School of Veterinary Medicine"),
                    ("NUR", "Nursing"),
                    ("WH", "Wharton"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                help_text='\nWhat school/program this attribute belongs to, e.g. `SAS` for `ASOC` restriction\nor `WH` for `WUOM` or `MODE` for `QP`. Options and meanings:\n<table width=100%><tr><td>"SAS"</td><td>"School of Arts and Sciences"</td></tr><tr><td>"LPS"</td><td>"College of Liberal and Professional Studies"</td></tr><tr><td>"SEAS"</td><td>"Engineering"</td></tr><tr><td>"DSGN"</td><td>"Design"</td></tr><tr><td>"GSE"</td><td>"Graduate School of Education"</td></tr><tr><td>"LAW"</td><td>"Law School"</td></tr><tr><td>"MED"</td><td>"School of Medicine"</td></tr><tr><td>"MODE"</td><td>"Grade Mode"</td></tr><tr><td>"VET"</td><td>"School of Veterinary Medicine"</td></tr><tr><td>"NUR"</td><td>"Nursing"</td></tr><tr><td>"WH"</td><td>"Wharton"</td></tr><tr><td>"OTHER"</td><td>"Other"</td></tr></table>',
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="ngssrestriction",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="\nThe code of the restriction.\n",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="ngssrestriction",
            name="restriction_type",
            field=models.CharField(
                db_index=True,
                help_text="\nWhat the restriction is based on (e.g., Campus).\n",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="pre_ngss_restrictions",
            field=models.ManyToManyField(
                blank=True,
                help_text="All pre-NGSS (deprecated since 2022C) registration Restriction objects to which this section is subject. This field will be empty for sections in 2022C or later.",
                related_name="sections",
                to="courses.prengssrestriction",
            ),
        ),
    ]
