# Generated by Django 4.0.4 on 2022-05-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0050_rename_include_or_exclude_ngssrestriction_inclusive_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngssrestriction",
            name="inclusive",
            field=models.BooleanField(
                help_text='\nWhether this is an include or exclude restriction. Corresponds to the `incl_excl_ind`\nresponse field. `True` if include (ie, `incl_excl_ind` is "I") and `False` if exclude ("E").\n'
            ),
        ),
    ]
