# Generated by Django 4.0.4 on 2022-06-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0050_rename_include_or_exclude_ngssrestriction_inclusive_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="school",
            field=models.CharField(
                choices=[
                    ("SAS", "School of Arts and Sciences"),
                    ("LPS", "College of Liberal and Professional Studies"),
                    ("SEAS", "Engineering"),
                    ("DSGN", "Design"),
                    ("GSE", "Graduate School of Education"),
                    ("LAW", "Law School"),
                    ("MED", "School of Medicine"),
                    ("MODE", "Grade Mode"),
                    ("VET", "School of Veterinary Medicine"),
                    ("NUR", "Nursing"),
                    ("WH", "Wharton"),
                ],
                db_index=True,
                help_text='\nWhat school/program this attribute belongs to, e.g. `SAS` for `ASOC` restriction\nor `WH` for `WUOM` or `MODE` for `QP`. Options and meanings:\n<table width=100%><tr><td>"SAS"</td><td>"School of Arts and Sciences"</td></tr><tr><td>"LPS"</td><td>"College of Liberal and Professional Studies"</td></tr><tr><td>"SEAS"</td><td>"Engineering"</td></tr><tr><td>"DSGN"</td><td>"Design"</td></tr><tr><td>"GSE"</td><td>"Graduate School of Education"</td></tr><tr><td>"LAW"</td><td>"Law School"</td></tr><tr><td>"MED"</td><td>"School of Medicine"</td></tr><tr><td>"MODE"</td><td>"Grade Mode"</td></tr><tr><td>"VET"</td><td>"School of Veterinary Medicine"</td></tr><tr><td>"NUR"</td><td>"Nursing"</td></tr><tr><td>"WH"</td><td>"Wharton"</td></tr></table>',
                max_length=5,
                null=True,
            ),
        ),
    ]
