# Generated by Django 4.0.4 on 2022-06-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0051_alter_attribute_school"),
        ("courses", "0051_alter_ngssrestriction_inclusive"),
    ]

    operations = []
