# Generated by Django 4.0.5 on 2022-06-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0052_merge_20220614_0027"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngssrestriction",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="\nThe code of the restriction.\n",
                max_length=16,
                unique=True,
            ),
        ),
    ]
