# Generated by Django 4.1.5 on 2023-01-15 16:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0053_alter_ngssrestriction_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngssrestriction",
            name="inclusive",
            field=models.BooleanField(
                help_text='\nWhether this is an include or exclude restriction. Corresponds to the `incl_excl_ind`\nresponse field. `True` if include (ie, `incl_excl_ind` is "I") and `False`\nif exclude ("E").\n'
            ),
        ),
    ]
