# Generated by Django 4.0.5 on 2022-08-14 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0053_alter_ngssrestriction_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        help_text="\nWhether the request was sent or accepted (0 if sent, \n1 if recieved and accepted, deleted if rejected)\n"
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField()),
                (
                    "requestReciever",
                    models.ForeignKey(
                        help_text="The person (user) who recieved the request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver",
                        to="courses.userprofile",
                    ),
                ),
                (
                    "requestSender",
                    models.ForeignKey(
                        help_text="The person (user) who sent the request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to="courses.userprofile",
                    ),
                ),
            ],
        ),
    ]
