# Generated by Django 4.0.5 on 2022-10-31 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0054_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="recipient",
            field=models.ForeignKey(
                default=None,
                help_text="The person (user) who recieved the request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_friendships",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friendship",
            name="sender",
            field=models.ForeignKey(
                default=None,
                help_text="The person (user) who sent the request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_friendships",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="friendship",
            name="accepted_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="status",
            field=models.CharField(
                choices=[("S", "Sent"), ("A", "Accepted"), ("R", "Rejected")],
                default="S",
                max_length=1,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together={("sender", "recipient")},
        ),
        migrations.RemoveField(
            model_name="friendship",
            name="requestReciever",
        ),
        migrations.RemoveField(
            model_name="friendship",
            name="requestSender",
        ),
    ]
