# Generated by Django 4.0.5 on 2023-01-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0056_alter_friendship_accepted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngssrestriction",
            name="inclusive",
            field=models.BooleanField(
                help_text='\nWhether this is an include or exclude restriction. Corresponds to the `incl_excl_ind`\nresponse field. `True` if include (ie, `incl_excl_ind` is "I") and `False`\nif exclude ("E").\n'
            ),
        ),
    ]
