# Generated by Django 3.2.18 on 2023-04-04 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0054_alter_ngssrestriction_inclusive"),
        ("courses", "0057_alter_ngssrestriction_inclusive"),
    ]

    operations = []
