# Generated by Django 3.2.18 on 2023-08-17 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0058_merge_20230403_2310"),
        ("courses", "0058_merge_20230712_1350"),
    ]

    operations = []
