# Generated by Django 3.2.21 on 2023-10-30 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0059_merge_20230816_2208"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="primary_listing",
            field=models.ForeignKey(
                blank=True,
                help_text="\nThe primary Course object with which this course is crosslisted. The set of crosslisted\ncourses to which this course belongs can thus be accessed with the related field\n`listing_set` on the `primary_listing` course. If a course doesn't have any crosslistings,\nits `primary_listing` foreign key will point to itself. If you call `.save()` on a course\nwithout setting its `primary_listing` field, the overridden `Course.save()` method will\nautomatically set its `primary_listing` to a self-reference.\n",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_set",
                to="courses.course",
            ),
        ),
    ]
