# Generated by Django 3.2.23 on 2023-11-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0060_alter_course_primary_listing"),
    ]

    operations = []
