# Generated by Django 3.2.23 on 2024-02-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_merge_20231112_1524'),
        ('courses', '0063_auto_20231212_1750'),
    ]

    operations = [
    ]
