# Generated by Django 3.2.23 on 2024-04-25 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0064_auto_20240120_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='downvotes',
            field=models.ManyToManyField(help_text='The number of downvotes a comment gets.', related_name='downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='section',
            field=models.ForeignKey(default=None, help_text='\nThe section with which a comment is associated. Section was chosen instead of courses\nfor hosting topics to support lower levels of filtering.\n', on_delete=django.db.models.deletion.CASCADE, to='courses.section'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(help_text='The number of upvotes a comment gets.', related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
