# Generated by Django 5.0.2 on 2024-04-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0064_auto_20240327_0249"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="historical_probabilities_fall",
            field=models.FloatField(
                default=0,
                help_text="\nThe historical probability of a student taking a course in this topic in the fall\nsemester, based on historical data. This field is recomputed nightly from the\n`parent_course` graph (in the recompute_soft_state cron job).\n",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="historical_probabilities_spring",
            field=models.FloatField(
                default=0,
                help_text="\nThe historical probability of a student taking a course in this topic in the spring\nsemester, based on historical data. This field is recomputed nightly from the\n`parent_course` graph (in the recompute_soft_state cron job).\n",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="historical_probabilities_summer",
            field=models.FloatField(
                default=0,
                help_text="\nThe historical probability of a student taking a course in this topic in the summer\nsemester, based on historical data. This field is recomputed nightly from the\n`parent_course` graph (in the recompute_soft_state cron job).\n",
            ),
        ),
    ]
