# Generated by Django 5.0.2 on 2025-09-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0065_topic_historical_probabilities_fall_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_been_onboarded",
            field=models.BooleanField(
                default=False,
                help_text="True if the user has completed onboarding and should not see the tutorial again.",
            ),
        ),
    ]
