# Generated by Django 5.0.2 on 2024-11-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0065_auto_20240425_2031"),
        ("courses", "0065_topic_historical_probabilities_fall_and_more"),
    ]

    operations = []
