# Generated by Django 3.2.23 on 2024-04-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0064_auto_20240120_1914"),
        ("courses", "0065_topic_historical_probabilities_fall_and_more"),
    ]

    operations = []
