# Generated by Django 5.0.2 on 2025-06-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0065_topic_historical_probabilities_fall_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="code",
            field=models.CharField(
                help_text="\nThe building code, for instance 570 for the Towne Building. To find the building code\nof a certain building, visit the [Penn Facilities Website](https://bit.ly/2BfE2FE).\n",
                max_length=5,
                unique=True,
            ),
        ),
    ]
