# Generated by Django 3.2.23 on 2024-02-16 05:34

from django.db import migrations, models
from courses.management.commands.recompute_soft_state import COURSE_CREDITS_RAW_SQL


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0065_auto_20240211_1321"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="credits",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                help_text="The number of credits this course takes. This is precomputed for efficiency.",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.RunSQL(
            COURSE_CREDITS_RAW_SQL,
        ),
    ]
