# Generated by Django 5.0.2 on 2024-10-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0065_topic_historical_probabilities_fall_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="count_for_hot_course",
            field=models.IntegerField(
                default=0,
                help_text="Keeps track of how often this course has been searched for on penn course review",
            ),
        ),
    ]
