# Generated by Django 3.2.23 on 2024-05-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_alter_section_activity'),
        ('courses', '0065_topic_historical_probabilities_fall_and_more'),
    ]

    operations = [
    ]
