# Generated by Django 5.0.2 on 2025-01-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0065_topic_historical_probabilities_fall_and_more"),
        ("plan", "0010_break"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="associated_break",
            field=models.ForeignKey(
                help_text="The Section object to which this class meeting belongs.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="plan.break",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="section",
            field=models.ForeignKey(
                help_text="The Section object to which this class meeting belongs.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="courses.section",
            ),
        ),
    ]
