# Generated by Django 5.0.2 on 2024-10-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0066_course_count_for_hot_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="count_for_hot_course",
        ),
        migrations.AddField(
            model_name="course",
            name="is_hot_course",
            field=models.BooleanField(
                default=False, help_text="is this course a hot course right now?"
            ),
        ),
    ]
