# Generated by Django 5.0.2 on 2025-02-16 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0066_meeting_associated_break_alter_meeting_section"),
        ("plan", "0014_break_unique_break_meeting_times_per_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="associated_break",
            field=models.ForeignKey(
                help_text="The Break object to which this meeting object belongs.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="plan.break",
            ),
        ),
        migrations.AddConstraint(
            model_name="meeting",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("section__isnull", True), ("associated_break__isnull", True), _connector="OR"
                ),
                fields=("section", "associated_break"),
                name="unique_meeting_either_section_or_break",
            ),
        ),
        migrations.AddConstraint(
            model_name="meeting",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("section__isnull", True), ("associated_break__isnull", True), _negated=True
                ),
                fields=("section", "associated_break"),
                name="meeting_must_have_section_or_break",
            ),
        ),
    ]
