# Generated by Django 5.0.2 on 2024-10-27 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0067_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="instructor",
            field=models.ForeignKey(
                help_text="\nThe instructor with which a comment is associated. Instructor was chosen instead of topics\nfor hosting comments because topics are SOFT STATE and are recomputed regularly.\n",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.instructor",
            ),
        ),
    ]
