# Generated by Django 5.0.2 on 2025-08-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0066_alter_building_code"),
        ("courses", "0067_alter_meeting_associated_break_and_more"),
    ]

    operations = []
