# Generated by Django 5.0.2 on 2025-12-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0068_merge_20250819_1758"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_been_onboarded",
            field=models.BooleanField(
                default=False,
                help_text="Defaults to False, changed to True once the user completes onboarding.",
            ),
        ),
    ]
