# Generated by Django 5.0.2 on 2025-10-01 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0066_userprofile_has_been_onboarded"),
        ("courses", "0068_merge_20250819_1758"),
    ]

    operations = []
