# Generated by Django 5.0.2 on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0068_merge_20250819_1758"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="prerequisite_courses",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Structured prerequisite links. If A requires B, then A.prerequisite_courses includes B."
                ),
                related_name="dependent_courses",
                symmetrical=False,
                to="courses.course",
            ),
        ),
    ]
