# Generated by Django 5.0.2 on 2026-02-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0068_merge_20250819_1758"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_quality",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="\nThe average course quality rating for this course, on a scale from 0 to 5 (precomputed for efficiency).\n",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="difficulty",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor_quality",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="work_required",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="course_quality",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="difficulty",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="instructor_quality",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="work_required",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
