# Generated by Django 5.0.2 on 2026-02-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0068_merge_20250819_1758"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="num_activities",
        ),
        migrations.AddField(
            model_name="course",
            name="course_quality",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="difficulty",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor_quality",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="work_required",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="course_quality",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="difficulty",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="instructor_quality",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="work_required",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="day",
            field=models.CharField(
                db_index=True,
                help_text="The single day on which the meeting takes place (one of M, T, W, R, or F).",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="end",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                help_text="The end time of the meeting; hh:mm is formatted as hh.mm = h+mm/100.",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="start",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                help_text="The start time of the meeting; hh:mm is formatted as hh.mm = h+mm/100.",
                max_digits=4,
            ),
        ),
    ]
