# Generated by Django 5.0.2 on 2025-10-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0069_merge_20250930_2239"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="has_been_onboarded",
            field=models.BooleanField(
                default=False,
                help_text="Defaults to False, changed to True once the user completes onboarding.",
            ),
        ),
    ]
