# Generated by Django 5.0.2 on 2026-02-26 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0069_course_course_quality_course_difficulty_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="difficulty",
            new_name="precompute_difficulty",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="instructor_quality",
            new_name="precompute_instructor_quality",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="work_required",
            new_name="precompute_work_required",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="course_quality",
            new_name="precompute_course_quality",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="difficulty",
            new_name="precompute_difficulty",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="instructor_quality",
            new_name="precompute_instructor_quality",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="work_required",
            new_name="precompute_work_required",
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_quality",
        ),
        migrations.AddField(
            model_name="course",
            name="annotation_expiration",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="\nThe expiration time for the annotations of this course, these fields should be refreshed\nevery month\n",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="precompute_course_quality",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="annotation_expiration",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="\nThe expiration time for the annotations of this section, these fields should\nbe refreshed every month\n",
            ),
        ),
    ]
