# Generated by Django 5.0.2 on 2026-02-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0069_course_course_quality_course_difficulty_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="num_activities",
        ),
    ]
