# Generated by Django 5.0.2 on 2026-02-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0070_remove_course_num_activities"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="num_activities",
            field=models.IntegerField(
                default=0,
                help_text="\nThe number of distinct activities belonging to this course (precomputed for efficiency).\nMaintained by the registrar import / recomputestats script.\n",
            ),
        ),
    ]
