# Generated by Django 5.0.2 on 2026-02-20 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0071_course_num_activities"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="annotations_expiration",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="\nThe expiration time for the annotations of this course, these fields should be refreshed\nevery month\n",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="annotation_expiration",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="\nThe expiration time for the annotations of this section, these fields should be refreshed\nevery month\n",
            ),
        ),
    ]
