# Generated by Django 5.0.2 on 2026-09-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0071_course_prerequisite_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="prerequisite_rule",
            field=models.JSONField(
                blank=True,
                help_text='\nWhich of `prerequisite_courses` are required, as parsed from Path@Penn class notes.\nA full code string ("CIS-1200"), {"text": "..."} for a condition that isn\'t a course\n(e.g. instructor permission), or {"and": [...]} / {"or": [...]} of these.\nNull if no course prerequisites are known.\n',
                null=True,
            ),
        ),
    ]
