# Generated by Django 2.2.12 on 2020-04-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_auto_20190525_2040"),
    ]

    operations = [
        migrations.RenameField(model_name="reviewbit", old_name="score", new_name="average",),
        migrations.AddField(
            model_name="review",
            name="enrollment",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review", name="form_type", field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review", name="responses", field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewbit",
            name="median",
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="reviewbit",
            name="rating0",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewbit",
            name="rating1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewbit",
            name="rating2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewbit",
            name="rating3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewbit",
            name="rating4",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewbit",
            name="stddev",
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True),
        ),
    ]
