# Generated by Django 2.2.12 on 2020-05-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_auto_20200428_1754"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewbit",
            name="field",
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
