# Generated by Django 3.0.6 on 2020-05-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_auto_20200512_1526"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="comments",
            field=models.TextField(blank=True),
        ),
    ]
