# Generated by Django 3.2.21 on 2024-01-30 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_alter_section_activity'),
        ('review', '0005_review_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecomputedReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(db_index=True, max_length=32)),
                ('num_sections', models.PositiveIntegerField()),
                ('average', models.DecimalField(decimal_places=5, max_digits=6)),
                ('semester', models.CharField(db_index=True, help_text='\nThe semester of the course (of the form YYYYx where x is A [for spring],\nB [summer], or C [fall]), e.g. `2019C` for fall 2019.\n', max_length=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.instructor')),
            ],
            options={
                'unique_together': {('course', 'instructor', 'field')},
                'index_together': {('course', 'instructor', 'field')},
            },
        ),
    ]
