# Generated by Django 5.0.2 on 2026-02-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0006_cachedreviewresponse"),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;"),
    ]
