# Generated by Django 5.0.2 on 2025-11-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0006_cachedreviewresponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedCourseReviews",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("department_id", models.IntegerField()),
                ("code", models.CharField(max_length=50)),
                ("semester", models.CharField(max_length=20)),
                ("title", models.TextField()),
                ("description", models.TextField(null=True)),
                ("syllabus_url", models.TextField(null=True)),
                ("full_code", models.CharField(max_length=100)),
                ("credits", models.FloatField()),
                ("prerequisites", models.TextField(null=True)),
                ("topic_id", models.IntegerField()),
                ("parent_course_id", models.IntegerField(null=True)),
                ("manually_set_parent_course", models.BooleanField()),
                ("primary_listing_id", models.IntegerField(null=True)),
                ("num_activities", models.IntegerField()),
                ("course_quality", models.FloatField(null=True)),
                ("difficulty", models.FloatField(null=True)),
                ("instructor_quality", models.FloatField(null=True)),
                ("work_required", models.FloatField(null=True)),
            ],
            options={
                "db_table": "cached_review_ratings",
                "managed": False,
            },
        ),
    ]
