# Generated by Django 5.0.2 on 2026-02-27 22:51

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0007_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("course_code", models.CharField(db_index=True, max_length=50)),
                ("text", models.TextField()),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "course_documents",
            },
        ),
    ]
